# Generated by Django 3.2.3 on 2021-06-02 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0002_auto_20210528_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=60)),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourapp.school')),
            ],
        ),
        migrations.CreateModel(
            name='Passing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_of_resumption',
            new_name='date_of_graduation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AlterField(
            model_name='student',
            name='School',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ourapp.school'),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ourapp.department')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourapp.school')),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=60)),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ourapp.department')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='Degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ourapp.degree'),
        ),
        migrations.AddField(
            model_name='student',
            name='Passing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ourapp.passing'),
        ),
    ]
